dogaegirl6mo/Dokgi

Dokgi/View/ ParagraphDetailView/ParagraphDetailViewController.swift, Dokgi/ViewModel/ParagraphDetailViewModel.swift
=> [Feat]#39-DetailViewModel수정

Dokgi.xcodeproj/project.pbxproj, Dokgi/Model/VerseModel.swift, Dokgi/View/ ParagraphDetailView/ParagraphDetailContainerView.swift, Dokgi/View/ ParagraphDetailView/ParagraphDetailViewController.swift, Dokgi/View/SegmentControlView.swift, Dokgi/ViewModel/ParagraphDetailViewModel.swift
- page segment구현
|   스크린샷   |
| :----------: |
| <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/33849ce4-f158-472a-aa26-1bc89a66be63" width ="250">|
- Resolved: #58
=> [Feat]#58-page segment구현

Dokgi.xcodeproj/project.pbxproj, Dokgi/View/BookDetailView/BookDetailViewController.swift, Dokgi/View/HomeView/HomeViewController.swift, Dokgi/View/LibraryView/LibrarySearchViewController.swift, Dokgi/View/TabBarVC.swift, Dokgi/ViewModel/BookDetailViewModel.swift, Dokgi/ViewModel/CoreDataManager.swift
- 책 상세화면의 구절 추가버튼을 이용하여 구절 추가시, 구절 추가가 완료되면 바로 책 상세화면에 반영
- 탭바 블러
| 탭바 블러 | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/129073316/98d84d34-9acc-459c-92fe-6fd5c88c1373" width ="250">|
- 위젯은 못했어요 여러분! 개발자계정 필요! 월요일에 상의한 뒤에 할게여
- Resolved: #59
=> 책 상세화면 데이터 반영, 탭바 블러

Dokgi/Network/BookManager.swift, Dokgi/View/AddVerseView/AddVerseVC.swift, Dokgi/View/AddVerseView/BookSearchVC.swift
- 구절 추가 화면 기능 및 UI 디테일
- Resolved: #55
=> Feat/#55 구절 추가 화면 기능 수정

Dokgi.xcodeproj/project.pbxproj, Dokgi/View/AddVerseView/AddVerseContainerLayout.swift, Dokgi/View/AddVerseView/AddVerseContainerView.swift, Dokgi/View/AddVerseView/AddVerseVC.swift, Dokgi/View/AddVerseView/KeywordCell.swift, Dokgi/View/BookDetailView/BookDetailViewController.swift, Dokgi/ViewModel/AddVerseViewModel.swift
- AddVerseVC의 파일을 분리했습니다
| GIF | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/59227948/e79a5f85-2320-4b5e-a44b-4dcb7766cd9f" width ="250">|
키워드셀의 테두리 색상은 일단 임시로 .lightSkyBlue로 변경했습니다
- Resolved: #66
=> Feat/#66 AddVerseVC 파일 분리

Dokgi/Application/AppDelegate.swift, Dokgi/Model/UserDefaultsKey.swift, Dokgi/Resource/Assets.xcassets/Color/BrightBlue.colorset/Contents.json, Dokgi/Resource/Assets.xcassets/Color/LavenderBlue.colorset/Contents.json, Dokgi/Resource/Assets.xcassets/Color/LavenderDarkBlue.colorset/Contents.json, Dokgi/View/SettingView/AlarmView.swift, Dokgi/View/SettingView/SettingViewController.swift, Dokgi/View/SettingView/TimePickerViewController.swift, Dokgi/ViewModel/DayTimeViewModel.swift
- 시간, 요일설정 오류 수정
- 수신 거절시 스위치 alert
|    alert    |   스크린샷   |
| <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/1d0c0567-c5ce-4dcb-81f0-d1ac9f76f168" width ="250"> | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/fafa82db-d4be-4fde-b77f-2515ecb22ffd" width ="250">|
- Resolved: #68
=> [Feat] 알림설정 화면 오류 수정 및 alert 구현

Dokgi/View/HomeView/CurrentLevelCell.swift, Dokgi/View/HomeView/HomeViewController.swift, Dokgi/ViewModel/HomeViewModel.swift
- 다음레벨 셀 디자인은 변경하여 적용하였습니다
| 다음레벨셀 디자인 변경 | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/161270615/e628a64a-0a8b-457b-8b64-7e6b852abbe1)|
- Resolved: #67
=> [Design]#67-다음레벨셀 디자인 변경

Dokgi.xcodeproj/project.pbxproj, Dokgi/View/LibraryView/LibraryCollectionViewCell.swift, Dokgi/View/LibraryView/LibrarySearchViewController.swift, Dokgi/ViewModel/LibrarySearchViewModel.swift
=> [Feat]#78-내서재 기능수정

Dokgi/View/HomeView/CurrentLevelCell.swift, Dokgi/View/HomeView/HomeViewController.swift, Dokgi/ViewModel/HomeViewModel.swift
- 퍼센트 반영
- 다음레벨셀  겹치는 오류수정
| 다음레벨 셀 | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/161270615/55348582-09e9-4a65-b7c7-35ce1cf2f227)|
- Resolved: #87
=> [Fix]#87-메인화면 버그 수정

Dokgi/View/ParagraphDetailView/KeywordCollectionViewCell.swift, Dokgi/View/ParagraphDetailView/ParagraphDetailContainerView.swift, Dokgi/View/ParagraphDetailView/ParagraphDetailViewController.swift, Dokgi/ViewModel/ParagraphDetailViewModel.swift
-  페이지 텍스트필드 부분 잘 안 눌림 → 크기 키우기
-  page 텍스트 필드 - 숫자 외 입력 제한
-  페이지 텍스트필드 앞 부분에 패딩 좀 주기
- 수정하기 → 세그먼트 기본값이 % → 기본선택을 페이지로 변경
- 키워드 색상 변경
- 키워드 개수 제한
| GIF | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/e044c839-d4c7-4a48-84fa-a5e33bafac09" width ="250">|
- Resolved: #88
=> [Feat] 구절상세화면 버그 수정

Dokgi/View/ParagraphView/ParagraphViewController.swift
- 내 구절 정렬 오류 수정
| GIF | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/6ad90eae-44c3-40b4-81c2-7b90b11c5080)|
- Resolved: #95
=> [Fix]#95-내 구절 정렬 오류 수정

Dokgi/View/BookDetailView/BookDetailViewController.swift
- 책상세 구절 잘리는 오류 수정 -> 셀높이 고정
| 책상세 구절셀 높이 고정 |<img width="319" alt="image" src="https://github.com/dogaegirl6mo/Dokgi/assets/161270615/87c97d2a-dd70-4082-a6bc-38098244fe6c">|
- Resolved: #93
=> [Fix]#93-책상세 구절 잘리는 오류 수정

Dokgi/View/LibraryView/LibraryCollectionViewCell.swift, Dokgi/View/LibraryView/LibrarySearchViewController.swift
=> [Fix]#91-내서재 정렬수정

Dokgi/View/LibraryView/LibrarySearchViewController.swift, Dokgi/View/ParagraphDetailView/ParagraphDetailViewController.swift
- alert구현
- 내서재 search, cancelButton 기능 구현
- Resolved: #100
=> [Fix]#100-구절 상세 페이지 alert구현

Dokgi.xcodeproj/project.pbxproj, Dokgi/Extension/addSubviewsExtension.swift, Dokgi/View/AddPassageView/Cell/KeywordCell.swift, Dokgi/View/AddPassageView/View/AddPassageContainerView.swift, Dokgi/View/AddPassageView/View/BookSearchContainerView.swift, Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift, Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift, Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift, Dokgi/ViewModel/BookSearchViewModel/BookSearchViewModel.swift
- 구절 추가 화면 파일분리
BookSearchVC 파일분리
- BookSearchContainerView 생성
AddPassageVC 파일분리
- 기존 파일들 수정
#104 
AddPassageVC 기존 파일들을 수정하다가 해당 이슈가 해결되었습니다
- Resolved: #107
=> Refactor/#107 구절 추가 화면 파일분리

Dokgi/Extension/DateExtension.swift, Dokgi/Model/CoreData/CoreDataManager.swift, Dokgi/View/BookDetailView/Cell/PassageTableViewCell.swift, Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift, Dokgi/View/LibraryView/ViewController/LibraryViewController.swift, Dokgi/View/PassageDetailView/Cell/KeywordCollectionViewCell.swift, Dokgi/ViewModel/BookDetailViewModel/BookDetailViewModel.swift
- 책 상세화면 코드 리팩토링
-  보라색 에러 해결
-  뷰모델 활용
-  컴포넌트 적용
- Resolved: #116
=> 책 상세 코드 리팩토링

Dokgi/View/HomeView/Cell/CurrentLevelCell.swift, Dokgi/View/HomeView/Cell/TodayPassageCell.swift, Dokgi/View/HomeView/View/HomeView.swift, Dokgi/View/HomeView/ViewController/HomeViewController.swift, Dokgi/View/PassageDetailView/Cell/KeywordCollectionViewCell.swift
- 코드리팩토링
- 기본색상 적용
- Resolved: #118
=> [Refactor]#118-홈 화면 코드 리팩토링

Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift, Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift, Dokgi/ViewModel/SettingViewModel/DayTimeViewModel.swift
- 구절 상세 화면 코어데이터 연결
- DayTimeViewModel 코어데이터 연결
- Resolved: #117
=> [Feat] 구절 상세화면, 알림 코어데이터 연결

Dokgi.xcodeproj/project.pbxproj, Dokgi/Model/CoreData/CoreDataManager.swift, Dokgi/View/BookDetailView/Cell/PassageTableViewCell.swift, Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift, Dokgi/ViewModel/BookDetailViewModel/BookDetailViewModel.swift, DokgiWidget/DokgiWidget.swift
- 책 상세, 위젯 코어데이터 연결
- 나중에 확인은 필요합니다
- Resolved: #121
=> 책 상세, 위젯 코어데이터 연결

Dokgi.xcodeproj/project.pbxproj, Dokgi/Extension/TextFieldExtension.swift, Dokgi/View/PassageDetailView/View/PassageDetailContainerView.swift, Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift, Dokgi/View/SettingView/ViewController/SettingViewController.swift, Dokgi/View/SettingView/ViewController/TimePickerViewController.swift
- 구절 상세 리팩토링
- 설정 리팩토링
- Resolved: #124
=> [Feat]#124-구절상세화면, 설정화면 리팩토링

Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift, Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
- AddPassage 코어데이터 연결
- `AddPassageViewModel` 수정
- `AddPassageViewController` 수정
실제 파일을 합쳐본 후 작동 확인을 해봐야합니다
- Resolved: #125
=> 구절 추가 화면 코어데이터 연결

Dokgi/Application/AppDelegate.swift, Dokgi/View/Components/BaseAlarmSettingSheetViewController.swift, Dokgi/View/SettingView/Cell/DayTableViewCell.swift, Dokgi/View/SettingView/View/AlarmView.swift, Dokgi/View/SettingView/ViewController/DaySelectViewController.swift, Dokgi/View/SettingView/ViewController/SettingViewController.swift, Dokgi/View/SettingView/ViewController/TimePickerViewController.swift, Dokgi/ViewModel/SettingViewModel/DayTimeViewModel.swift
- 알림데이터 업데이트 → 앱키면 실행 멍청하게 까먹
- 알림 설정 안 됐을시 알림 시간설정 비활성화 느낌
- 다크모드 대응?
| GIF | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/6fa798de-b850-4bb1-942d-c1e676bf5419" width ="250">|
- Resolved: #129
=> Feat/#129 알림및 설정화면 오류수정

Dokgi/View/LibraryView/ViewController/LibraryViewController.swift, Dokgi/View/PassageView/ViewController/PassageViewController.swift, Dokgi/ViewModel/LibraryViewModel/LibraryViewModel.swift, Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
- 내 서재, 구절 코어데이터 연결
- 오류 해결에 중점을 두고 코어데이터 연결했습니다.
- 코드를 수정하다보니 리팩토링을 하면 좋을 것 같다고 생각되는 부분이 코어데이터와 연결된 부분이어서 큰 수정은 하지 않았습니다.
- 현재 HomeViewModel만 오류가 납니다 
- Resolved: #138
=> 내 서재, 구절 코어데이터 연결

Dokgi/View/HomeView/View/HomeView.swift, Dokgi/View/HomeView/ViewController/HomeViewController.swift, Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
- 홈 화면 코어데이터 연결
- LivraryViewModel 에서만 오류가 납니다
- Resolved: #128
=> [Feat]#128-홈 화면 코어데이터 연결

Dokgi/Model/CoreData/CoreDataManager.swift, Dokgi/View/PassageView/Cell/PassageCollectionViewCell.swift, Dokgi/View/PassageView/ViewController/PassageViewController.swift, Dokgi/ViewModel/PassageViewModel/PassageViewModel.swift
- 선택 버튼 후 삭제 시 : alert 창 띄우기
- 구절 삭제 중에 구절 상세 화면 이동 못하게
- 다크모드 대응
| GIF | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/887d8e8c-0151-4511-9941-70716df45257" width ="250">|
- Resolved: #148
=> [Feat] 구절화면

Dokgi/View/HomeView/Cell/CurrentLevelCell.swift, Dokgi/View/HomeView/View/HomeView.swift, Dokgi/View/HomeView/ViewController/HomeViewController.swift
- 현재 구절 길이 다이나믹셀 적용했습니다. 가장 큰 폰트를 적용할 때만 잘려서 가장 큰 폰트를 적용했을 때만 셀의 높이를 수정했습니다
| 다이나믹셀 적용 |<img width="241" alt="image" src="https://github.com/dogaegirl6mo/Dokgi/assets/161270615/98a9040e-68cb-41f0-ac60-0a7374b58af3">|
- Resolved: #150
=> [Feat]#150- 홈 화면 수정

Dokgi.xcodeproj/project.pbxproj, Dokgi/Network/BookManager.swift, Dokgi/Network/BookModel.swift, Dokgi/Resource/Assets.xcassets/Color/searchButtonBlue.colorset/Contents.json, Dokgi/View/AddPassageView/Cell/BookCell.swift, Dokgi/View/AddPassageView/View/AddPassageContainerView.swift, Dokgi/View/AddPassageView/View/BookSearchContainerView.swift, Dokgi/View/AddPassageView/View/InfoView.swift, Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift, Dokgi/View/Components/SearchBar.swift, Dokgi/ViewModel/AddPassageViewModel/AddPassageViewModel.swift
- 구절 추가 화면 수정
텍스트 필드 오류 관련해서 논의해야합니다
SearchBar 컴포넌트에 textColor 속성을 추가했습니다
공통으로 사용하는 뷰들은 다크모드때 입력값이 보이도록 했습니다
- Resolved: #140
=> 구절 추가 화면 수정

Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift, Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
- 책 상세 다크모드 대응 및 오류 수정
|    기능    |   스크린샷1   |   스크린샷2   |
| :-------------: | :----------: | :----------: |
| 책 상세 다크모드 대응 및 오류 수정 | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/14a67f9e-8a31-4caa-bde1-4d49a930dc76)| ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/aa06c53e-9b10-4766-a95e-82182905055a)| 
- Resolved: #156
=> [Fix]#156-책 상세 다크모드 대응 및 오류 수정

Dokgi/Base.lproj/LaunchScreen.storyboard
- 런치스크린 다크모드 대응
| GIF | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/b1033472-cfbf-40bb-b6a9-d0f3f22628bf)|
- Resolved: #158
=> [Feat]#158-런치스크린 다크모드 대응

Dokgi/Model/CoreData/CoreDataManager.swift, Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift, Dokgi/View/PassageView/ViewController/PassageViewController.swift, Dokgi/View/TabBarView/TabBarViewController.swift, Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
- 글씨만 바뀌고 기능이 그대로
- 기본 순서가 최신순이 아님
- 삭제 alert “확인” 버튼 볼드
- 검색 중에 구절 추가시 구절 화면에 반영
- 구절 수정시 오래된순 순서가 바뀜 (최근 고친 구절의 순서가 뒤로감)
- 복사 하고 나면 토스트를 먹기
|    toast    |   alert   |
| <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/576a86ce-db77-47a1-bfd5-3c9598637eed" width ="250">| <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/707dc925-455b-4392-9c26-cb24be3c1b81" width ="250">|
- Resolved: #159
=> [Fix] 구절화면 오류 수정2차

Dokgi/View/HomeView/ViewController/HomeViewController.swift, Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
- 구절 5개 까지 오늘의 구절에 바로 반영
-  5개 미만 일시 오늘의 구절을 설명하는 문구 나머지 셀에 보여주기
| 오늘의 구절 | ![2024-06-271 56 06-ezgif com-video-to-gif-converter](https://github.com/dogaegirl6mo/Dokgi/assets/161270615/9a958a01-dc9f-4bc2-89ae-250848fafa84)|
스크린샷 gif 입니다
- Resolved: #164
=> [Feat]#164-오늘의구절 수정

Dokgi.xcodeproj/project.pbxproj, Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift, Dokgi/View/TabBarView/TabBarViewController.swift, DokgiWidget/DokgiWidget.swift
- 위젯 오류
- 책 상세에서 구절 추가시 구절 추가한 것 바로 반영
- 화면 세로 고정
| 위젯 | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/129073316/ff8f7513-c9bc-45e2-b003-1c2fa6bcce8a" width ="250">|
- 정신이 없네여...
- Resolved: #162
=> Fix/#162 위젯 오류, 구절 추가하면 바로 반영

Dokgi/View/LibraryView/Cell/LibraryCollectionViewCell.swift, Dokgi/View/LibraryView/ViewController/LibraryCollectionView.swift
- 내 서재 오토레이아웃 수정
| 서재 | ![Simulator Screenshot - iPhone 15 Pro - 2024-06-27 at 11 06 50](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/24e08d27-7a1e-45f2-9295-14864491dea7)|
- Resolved: #165
=> Fix/#165 내 서재 오토레이아웃 수정

Dokgi/Model/CoreData/CoreDataManager.swift, Dokgi/View/AddPassageView/View/AddPassageContainerView.swift, Dokgi/View/AddPassageView/View/BookSearchContainerView.swift, Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift, Dokgi/View/LibraryView/ViewController/LibraryViewController.swift
- 서재 검색 중 구절 추가 시 / 책 추가 구절 스캔 버튼 / 책 검색 최근 검색어 수정
- 서재 검색 중 구절 추가 시 전체가 보이는 문제
- 책 추가 구절 스캔 버튼 수정
- 책 검색 최근 검색어 리스트 글자 최대 시 잘리는 문제
|    기능    |   스크린샷   |  스크린샷2   |  스크린샷3   |
| :-------------: | :----------: | :----------: | :----------: |
| 오류수정 | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/0caca70e-9a1f-43db-a019-405daccdea96)| ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/ec976ac9-ecb8-43a4-9d5d-3c2490342cd3)| ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/e36fe87f-e772-4122-8a3a-bd5338302d46)|
- Resolved: #171
=> Fix/#171 서재 검색 중 구절 추가 시 / 책 추가 구절 스캔 버튼 / 책 검색 최근 검색어 수정

Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift
- OCR 텍스트뷰 textColor 수정
OCR 텍스트뷰 textColor 수정
| 다크모드 | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/59227948/5dc96f43-be55-42d4-a86c-f371e9d075a3" width ="250">|
| 라이트모드 | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/59227948/37e973ea-8a94-417c-b861-4a4058cd1f48" width ="250">|
꼼꼼히 살폈어야 하는데 죄송합니다
- Resolved: #182
=> [Fix]#182-OCR 텍스트뷰 textColor 수정

Dokgi/View/AddPassageView/View/InfoView.swift, Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift, Dokgi/View/HomeView/Cell/CurrentLevelCell.swift, Dokgi/View/PassageDetailView/ViewController/PassageDetailViewController.swift, DokgiWidget/DokgiWidget.swift
- 메인
Level 1을 다 달성하면… 레이블이 가운데로 배치해두신 것 같은데 오른쪽은 여백이 있어보이는데 왼쪽은 닿아있습니다,, 왜 그럴까요..?
- 구절 상세
글자 최대일 때 → 수정하기 옆 연필 너무 미니미해요..
- 구절 추가
작가가 여러 명일 때 저렇게 나타남 → 한 줄로 빼서 … 처리 되는 게 좋겠습니다
- 책상세
스크롤을 제일 밑으로 내렸을 때, 구절셀(하늘색)과 구절 추가하기 버튼이 맞닿는 것보다 약간 여백을 주는 게 어떨까요?→ 구절 추가하기 버튼이 플로팅 버튼 입니다
|    메인    |   구절 상세   |
| <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/f52cc49d-48fb-4c5b-ba7e-ae281a358e3e" width ="250"> | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/ad741806-7820-4073-80dd-47a42defcad9" width ="250">|
|    구절 추가    |   책 상세   |
| <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/6fcd0d52-de15-4e1c-a73b-8003f180edcd" width ="250"> | <img src = …
=> [Fix] 오류수정 3차

Dokgi/View/Components/CustomNavigationController.swift, Dokgi/View/PassageDetailView/View/PassageDetailContainerView.swift, Dokgi/View/SettingView/ViewController/SettingViewController.swift
- 네비게이션 제스처 추가
- 키워드가 없을 때 : 구절 클릭 후 구절 상세에서 ‘키워드가 없습니다’ 레이블이 
2024.07.03 이나 #페이지처럼 오른쪽에 위치
|    기능    |  키워드 없을때   |
|  <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/b199c6fc-7a71-488c-b8f7-79f81a0aa456" width ="250"> | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/142602172/e84a0fd0-5aa9-40df-a1e3-b69fca4ce640" width ="250">|
- Resolved: #192
=> [Fix] 네비게이션 및 구절상세 키워드 수정

Dokgi/View/AddPassageView/ViewController/BookSearchViewController.swift, Dokgi/ViewModel/BookSearchViewModel/BookSearchViewModel.swift, Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift
- 오류 수정 5차 구절 추가 
- 자모음 하나씩 입력 될때마다 최근 검색어에 저장
- 최근 검색어 x버튼과 label 간격 넓히기
| x버튼 간격 | <img src = "https://github.com/dogaegirl6mo/Dokgi/assets/59227948/b5f92e15-8a86-4380-b240-1739ba261a0b" width ="250">|
- Resolved: #191
=> Fix/#191 오류 수정 5차 구절 추가

Dokgi/View/AddPassageView/ViewController/AddPassageViewController.swift, Dokgi/View/BookDetailView/ViewController/BookDetailViewController.swift
- 서재에서 책 상세 넘어갈 때 서재 정렬 바뀜 (오래된 순으로 바뀌는 듯) - 잠깐 바뀜
- 서재-책상세-서재-책상세-서재에서 검색-터짐
- Resolved: #194
=> [Fix]#194-서재오류 해결

Dokgi/View/PassageView/ViewController/PassageViewController.swift
- 오류 5차 수정 구절 화면
-  구절 선택 말고 편집, 완료도 파랑색으로
- 구절 편집시에 완료 안누르고 다른탭으로 이동했다가 구절탭으로 돌아오면 편집 모드 유지됨
|    기능    |   스크린샷1   | 스크린샷2   |
| :-------------: | :----------: | :----------: |
| 구절화면 | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/4d06b8d3-8597-4541-ae2f-ee87e072d476) | ![image](https://github.com/dogaegirl6mo/Dokgi/assets/162525811/3e4515eb-d63c-463a-8598-2438100a8d2d) | 
- Resolved: #190
=> [Fix] 오류 5차 수정 구절 화면

Dokgi.xcodeproj/project.pbxproj, Dokgi/View/HomeView/Cell/CurrentLevelCell.swift, Dokgi/View/HomeView/ViewController/HomeViewController.swift, Dokgi/View/PassageView/ViewController/PassageViewController.swift, Dokgi/ViewModel/HomeViewModel/HomeViewModel.swift, Dokgi/ViewModel/PassageDetailViewModel/PassageDetailViewModel.swift
- 메인 터진 것 수정,,
5개 이상일 때 삭제한 데이터가 반영 안되어서 난 오류
- Resolved: #199
=> [Fix]#199-홈화면오류수정

Dokgi.xcodeproj/project.pbxproj, Dokgi/View/Components/BaseLibraryAndPassageViewController.swift, Dokgi/View/PassageView/ViewController/PassageViewController.swift
- 오류 7차 해결
- 구절
- 스크롤이 안됨 (데이터 변경이 있을 때 안되는 듯)
⇒ 스크롤 시도 시 구절이 사라졌다가 나타남(반짝반짝…)
⇒ 다른 창이나 정렬 버튼, 편집 버튼처럼 다른 버튼을 눌렀을 때는 됨
- 내 서재
- 검색 상태가 계속 남아있음 (다른 탭 방문, 구절 추가 등 다른 행동 해도)
- Resolved: #201
=> [Fix]#201-오류 7차
